# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpotifyHelper' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpotifyHelper
   pod 'Alamofire', '~> 4.4'
   pod 'SwiftyJSON'
   pod 'SDWebImage', '~> 3.8' 
  target 'SpotifyHelperTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpotifyHelperUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
